vote:
  image: jackmontyorg/vote:master
  ports:
    - 5000:80
  links:
    - redis:redis

redis:
  image: redis:alpine

db:
  image: postgres:9.4
  environment: 
    POSTGRES_HOST_AUTH_METHOD: trust

result:
  image: jackmontyorg/result:master
  ports: 
    - 5001:4000
  links:
    - db:db

worker:
  image: jackmontyorg/worker:master
  links:
    - redis:redis
    - db:db
